// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents service health events that may affect Google Cloud products.
/// Event resource is a read-only view and does not allow any modifications. All
/// fields are output only.
public struct Event: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the event. Unique name of the event in
  /// this scope including project and location using the form
  /// `projects/{project_id}/locations/{location}/events/{event_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Brief description for the event.
  public var title: Swift.String = Swift.String()

  /// Output only. Free-form, human-readable description.
  public var description: Swift.String = Swift.String()

  /// Output only. The category of the event.
  public var category: Event.EventCategory = Event.EventCategory()

  /// Output only. The detailed category of the event.
  public var detailedCategory: Event.DetailedCategory = Event.DetailedCategory()

  /// Output only. The current state of the event.
  public var state: Event.State = Event.State()

  /// Output only. The current detailed state of the incident.
  public var detailedState: Event.DetailedState = Event.DetailedState()

  /// Google Cloud products and locations impacted by the event.
  public var eventImpacts: [EventImpact] = []

  /// Output only. Communicates why a given event is deemed relevant in the
  /// context of a given project.
  public var relevance: Event.Relevance = Event.Relevance()

  /// Output only. Event updates are correspondence from Google.
  public var updates: [EventUpdate] = []

  /// Output only. When `detailed_state`=`MERGED`, `parent_event` contains the
  /// name of the parent event. All further updates will be published to the
  /// parent event.
  public var parentEvent: Swift.String = Swift.String()

  /// Output only. The time when the event was last modified.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The start time of the event, if applicable.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Output only. The end time of the event, if applicable.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the next update can be expected.
  public var nextUpdateTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let title = CodingKeys(stringValue: "title")
    static let description = CodingKeys(stringValue: "description")
    static let category = CodingKeys(stringValue: "category")
    static let detailedCategory = CodingKeys(stringValue: "detailedCategory")
    static let state = CodingKeys(stringValue: "state")
    static let detailedState = CodingKeys(stringValue: "detailedState")
    static let eventImpacts = CodingKeys(stringValue: "eventImpacts")
    static let relevance = CodingKeys(stringValue: "relevance")
    static let updates = CodingKeys(stringValue: "updates")
    static let parentEvent = CodingKeys(stringValue: "parentEvent")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let nextUpdateTime = CodingKeys(stringValue: "nextUpdateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "title",
      "description",
      "category",
      "detailedCategory",
      "state",
      "detailedState",
      "eventImpacts",
      "relevance",
      "updates",
      "parentEvent",
      "updateTime",
      "startTime",
      "endTime",
      "nextUpdateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
      self.title = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Event.EventCategory.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(
      Event.DetailedCategory.self, forKey: .detailedCategory)
    {
      self.detailedCategory = value
    }
    if let value = try container.decodeIfPresent(Event.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Event.DetailedState.self, forKey: .detailedState) {
      self.detailedState = value
    }
    if let value = try container.decodeIfPresent([EventImpact].self, forKey: .eventImpacts) {
      self.eventImpacts = value
    }
    if let value = try container.decodeIfPresent(Event.Relevance.self, forKey: .relevance) {
      self.relevance = value
    }
    if let value = try container.decodeIfPresent([EventUpdate].self, forKey: .updates) {
      self.updates = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parentEvent) {
      self.parentEvent = value
    }
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    self.nextUpdateTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .nextUpdateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.title, forKey: .title)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.detailedCategory, forKey: .detailedCategory)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.detailedState, forKey: .detailedState)
    try container.encode(self.eventImpacts, forKey: .eventImpacts)
    try container.encode(self.relevance, forKey: .relevance)
    try container.encode(self.updates, forKey: .updates)
    try container.encode(self.parentEvent, forKey: .parentEvent)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.nextUpdateTime, forKey: .nextUpdateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The category of the event. This enum lists all possible categories of
  /// event.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum EventCategory: Codable, Equatable, Sendable {
    /// Unspecified category.
    case unspecified
    /// Event category for service outage or degradation.
    case incident
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .incident: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_CATEGORY_UNSPECIFIED"
      case .incident: return "INCIDENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_CATEGORY_UNSPECIFIED": self = .unspecified
      case "INCIDENT": self = .incident
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .incident
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EVENT_CATEGORY_UNSPECIFIED")
      case .incident: return try container.encode("INCIDENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The detailed category of an event. Contains all possible states for all
  /// event categories.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DetailedCategory: Codable, Equatable, Sendable {
    /// Unspecified detailed category.
    case unspecified
    /// Indicates an event with category INCIDENT has a confirmed impact to at
    /// least one Google Cloud product.
    case confirmedIncident
    /// Indicates an event with category INCIDENT is under investigation to
    /// determine if it has a confirmed impact on any Google Cloud products.
    case emergingIncident
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .confirmedIncident: return 1
      case .emergingIncident: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DETAILED_CATEGORY_UNSPECIFIED"
      case .confirmedIncident: return "CONFIRMED_INCIDENT"
      case .emergingIncident: return "EMERGING_INCIDENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DetailedCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DETAILED_CATEGORY_UNSPECIFIED": self = .unspecified
      case "CONFIRMED_INCIDENT": self = .confirmedIncident
      case "EMERGING_INCIDENT": self = .emergingIncident
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DetailedCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .confirmedIncident
      case 2: self = .emergingIncident
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DETAILED_CATEGORY_UNSPECIFIED")
      case .confirmedIncident: return try container.encode("CONFIRMED_INCIDENT")
      case .emergingIncident: return try container.encode("EMERGING_INCIDENT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state of the event. This enum lists all possible states of event.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Event is actively affecting a Google Cloud product and will continue to
    /// receive updates.
    case active
    /// Event is no longer affecting the Google Cloud product or has been merged
    /// with another event.
    case closed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .closed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .closed: return "CLOSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CLOSED": self = .closed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .closed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .closed: return try container.encode("CLOSED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The detailed state of the incident. This enum lists all possible detailed
  /// states of an incident.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DetailedState: Codable, Equatable, Sendable {
    /// Unspecified detail state.
    case unspecified
    /// Google engineers are actively investigating the event to determine the
    /// impact.
    case emerging
    /// The incident is confirmed and impacting at least one Google Cloud
    /// product. Ongoing status updates will be provided until it is resolved.
    case confirmed
    /// The incident is no longer affecting any Google Cloud product, and there
    /// will be no further updates.
    case resolved
    /// The incident was merged into a parent incident. All further updates will
    /// be published to the parent only. The `parent_event` field contains the
    /// name of the parent.
    case merged
    /// The incident was automatically closed because of the following reasons:
    ///
    ///  * The impact of the incident could not be confirmed.
    ///  * The incident was intermittent or resolved itself.
    ///
    ///  The incident does not have a resolution because no action or
    ///  investigation happened. If it is intermittent, the incident may reopen.
    case autoClosed
    /// Upon investigation, Google engineers concluded that the incident is not
    /// affecting a Google Cloud product. This state can change if the incident
    /// is reviewed again.
    case falsePositive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .emerging: return 1
      case .confirmed: return 2
      case .resolved: return 3
      case .merged: return 4
      case .autoClosed: return 9
      case .falsePositive: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DETAILED_STATE_UNSPECIFIED"
      case .emerging: return "EMERGING"
      case .confirmed: return "CONFIRMED"
      case .resolved: return "RESOLVED"
      case .merged: return "MERGED"
      case .autoClosed: return "AUTO_CLOSED"
      case .falsePositive: return "FALSE_POSITIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DetailedState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DETAILED_STATE_UNSPECIFIED": self = .unspecified
      case "EMERGING": self = .emerging
      case "CONFIRMED": self = .confirmed
      case "RESOLVED": self = .resolved
      case "MERGED": self = .merged
      case "AUTO_CLOSED": self = .autoClosed
      case "FALSE_POSITIVE": self = .falsePositive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DetailedState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .emerging
      case 2: self = .confirmed
      case 3: self = .resolved
      case 4: self = .merged
      case 9: self = .autoClosed
      case 10: self = .falsePositive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DETAILED_STATE_UNSPECIFIED")
      case .emerging: return try container.encode("EMERGING")
      case .confirmed: return try container.encode("CONFIRMED")
      case .resolved: return try container.encode("RESOLVED")
      case .merged: return try container.encode("MERGED")
      case .autoClosed: return try container.encode("AUTO_CLOSED")
      case .falsePositive: return try container.encode("FALSE_POSITIVE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Communicates why a given incident is deemed relevant in the context of a
  /// given project. This enum lists all possible detailed states of relevance.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Relevance: Codable, Equatable, Sendable {
    /// Unspecified relevance.
    case unspecified
    /// The relevance of the incident to the project is unknown.
    case unknown
    /// The incident does not impact the project.
    case notImpacted
    /// The incident is associated with a Google Cloud product your project uses,
    /// but the incident may not be impacting your project. For example, the
    /// incident may be impacting a Google Cloud product that your project uses,
    /// but in a location that your project does not use.
    case partiallyRelated
    /// The incident has a direct connection with your project and impacts a
    /// Google Cloud product in a location your project uses.
    case related
    /// The incident is verified to be impacting your project.
    case impacted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknown: return 2
      case .notImpacted: return 6
      case .partiallyRelated: return 7
      case .related: return 8
      case .impacted: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RELEVANCE_UNSPECIFIED"
      case .unknown: return "UNKNOWN"
      case .notImpacted: return "NOT_IMPACTED"
      case .partiallyRelated: return "PARTIALLY_RELATED"
      case .related: return "RELATED"
      case .impacted: return "IMPACTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Relevance/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RELEVANCE_UNSPECIFIED": self = .unspecified
      case "UNKNOWN": self = .unknown
      case "NOT_IMPACTED": self = .notImpacted
      case "PARTIALLY_RELATED": self = .partiallyRelated
      case "RELATED": self = .related
      case "IMPACTED": self = .impacted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Relevance/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .unknown
      case 6: self = .notImpacted
      case 7: self = .partiallyRelated
      case 8: self = .related
      case 9: self = .impacted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RELEVANCE_UNSPECIFIED")
      case .unknown: return try container.encode("UNKNOWN")
      case .notImpacted: return try container.encode("NOT_IMPACTED")
      case .partiallyRelated: return try container.encode("PARTIALLY_RELATED")
      case .related: return try container.encode("RELATED")
      case .impacted: return try container.encode("IMPACTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.Event"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
