// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Requests list of events that affect an organization.
public struct ListOrganizationEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent value using the form
  /// `organizations/{organization_id}/locations/{location}/organizationEvents`.
  ///
  /// `organization_id` - ID (number) of the project that contains the event. To
  /// get your `organization_id`, see
  /// [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).<br>
  /// `location` - The location to get the service health events from. To
  /// retrieve service health events of category = INCIDENT, use `location` =
  /// `global`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of events that should be returned.  Acceptable
  /// values are `1` to `100`, inclusive. (The default value is `10`.) If more
  /// results are available, the service returns a `next_page_token` that you can
  /// use to get the next page of results in subsequent list requests. The
  /// service may return fewer events than the requested `page_size`.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  ///
  /// Provide Page token returned by a previous `ListOrganizationEvents` call to
  /// retrieve the next page of results.
  ///
  /// When paginating, all other parameters provided to
  /// `ListOrganizationEvents` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters resources listed in the
  /// response. The expression takes the following forms:
  ///
  /// *   field=value for `category` and `state`
  /// *   field &lt;, >, &lt;=, or >= value for `update_time`
  ///
  /// Examples: `category=INCIDENT`, `update_time>="2000-01-01T11:30:00-04:00"`
  ///
  /// Multiple filter queries are space-separated. Example:
  /// `category=INCIDENT state=ACTIVE`.
  ///
  /// By default, each expression is an AND expression. However, you can include
  /// AND and OR expressions explicitly.
  ///
  /// Filter is supported for the following fields: `category`, `state`,
  /// `update_time`
  public var filter: Swift.String = Swift.String()

  /// Optional. OrganizationEvent fields to include in response.
  public var view: OrganizationEventView = OrganizationEventView()

  /// Initialize a new instance of `ListOrganizationEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOrganizationEventsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.ListOrganizationEventsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
