// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response to request for listing organization events.
public struct ListOrganizationEventsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// Output only. List of organization events affecting an organization.
  public var organizationEvents: [OrganizationEvent] = []

  /// Output only. The continuation token, used to page through large result
  /// sets. Provide this value in a subsequent request as `page_token` to
  /// retrieve the next page.
  ///
  /// If this field is not present, there are no subsequent results.
  public var nextPageToken: Swift.String = Swift.String()

  /// Output only. Locations that could not be reached.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ListOrganizationEventsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOrganizationEventsResponse().with { $0.organizationEvents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.ListOrganizationEventsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [OrganizationEvent] {
    return self.organizationEvents
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
