// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Requests list of events.
public struct ListEventsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Parent value using the form
  /// `projects/{project_id}/locations/{location}/events`.
  ///
  /// `project_id` - ID of the project for which to list service health
  /// events.
  /// `location` - The location to get the service health events from.
  /// To retrieve service health events of category = INCIDENT, use `location` =
  /// `global`.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of events that should be returned.  Acceptable
  /// values are 1 to 100, inclusive. (The default value is 10.) If more results
  /// are available, the service returns a next_page_token that you can use to
  /// get the next page of results in subsequent list requests. The service may
  /// return fewer events than the requested page_size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  /// Provide Page token returned by a previous `ListEvents` call to retrieve the
  /// next page of results. When paginating, all other parameters provided to
  /// `ListEvents` must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters resources listed in the
  /// response. The expression takes the following forms: <br>
  /// *   field=value for `category` and `state`<br>
  /// *   field &lt;, >, &lt;=, or >= value for `update_time` <br>
  /// Examples: `category=INCIDENT`, `update_time>="2000-01-01T11:30:00-04:00"`,
  /// `event_impacts.product.product_name:"Eventarc"`
  /// <br>
  ///
  /// Multiple filter queries are separated by spaces. Example:
  /// `category=INCIDENT state=ACTIVE`.
  ///
  /// By default, each expression is an AND expression. However, you can include
  /// AND and OR expressions explicitly.
  ///
  /// Filter is supported for the following fields: `category`, `state`,
  /// `update_time`, `event_impacts.product.product_name`
  public var filter: Swift.String = Swift.String()

  /// Optional. Event fields to include in response.
  public var view: EventView = EventView()

  /// Initialize a new instance of `ListEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEventsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.ListEventsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
