// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Requests list of projects under an organization affected by an event.
public struct ListOrganizationImpactsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent value using the form
  /// `organizations/{organization_id}/locations/{location}/organizationImpacts`.
  ///
  /// `organization_id` - ID (number) of the project that contains the event. To
  /// get your `organization_id`, see
  /// [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of events that should be returned. Acceptable
  /// values are `1` to `100`, inclusive. The default value is `10`.
  ///
  ///  If more results are available, the service returns a
  /// `next_page_token` that can be used to get the next page of results in
  /// subsequent list requests. The service may return fewer
  /// [impacts](/service-health/docs/reference/rest/v1beta/organizations.locations.organizationImpacts#OrganizationImpact)
  /// than the requested `page_size`.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A token identifying a page of results the server should return.
  ///
  /// Provide `page_token` returned by a previous `ListOrganizationImpacts` call
  /// to retrieve the next page of results.
  ///
  /// When paginating, all other parameters provided to `ListOrganizationImpacts`
  /// must match the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter expression that filters resources listed in the
  /// response. The expression is in the form of `field:value` for checking if a
  /// repeated field contains a value.
  ///
  /// Example:
  /// `events:organizations%2F{organization_id}%2Flocations%2Fglobal%2ForganizationEvents%2Fevent-id`
  ///
  /// To get your `{organization_id}`, see
  /// [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).
  ///
  /// Multiple filter queries are separated by spaces.
  ///
  /// By default, each expression is an AND expression. However, you can include
  /// AND and OR expressions explicitly.
  /// Filter is supported for the following fields: `events`.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListOrganizationImpactsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOrganizationImpactsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.ListOrganizationImpactsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
