// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents impact to assets at organizational level. It is a read-only view
/// and does not allow any modifications.
public struct OrganizationImpact: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Unique name of the organization impact in this
  /// scope including organization and location using the form
  /// `organizations/{organization_id}/locations/{location}/organizationImpacts/{organization_impact_id}`.
  ///
  /// `organization_id` - ID (number) of the organization that contains the
  /// event. To get your `organization_id`, see
  /// [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).<br>
  /// `organization_impact_id` - ID of the [OrganizationImpact
  /// resource](/service-health/docs/reference/rest/v1beta/organizations.locations.organizationImpacts#OrganizationImpact).
  public var name: Swift.String = Swift.String()

  /// Output only. A list of event names impacting the asset.
  public var events: [Swift.String] = []

  /// Output only. Google Cloud asset possibly impacted by the specified events.
  public var asset: Asset? = nil

  /// Output only. The time when the affected project was last modified.
  public var updateTime: GoogleWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OrganizationImpact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrganizationImpact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let events = CodingKeys(stringValue: "events")
    static let asset = CodingKeys(stringValue: "asset")
    static let updateTime = CodingKeys(stringValue: "updateTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "events",
      "asset",
      "updateTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .events) {
      self.events = value
    }
    self.asset = try container.decodeIfPresent(Asset.self, forKey: .asset)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.events, forKey: .events)
    try container.encodeIfPresent(self.asset, forKey: .asset)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.OrganizationImpact"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
