// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents impact to assets at organizational level. It is a read-only view
/// and does not allow any modifications.
public struct OrganizationImpact: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Unique name of the organization impact in this
  /// scope including organization and location using the form
  /// `organizations/{organization_id}/locations/{location}/organizationImpacts/{organization_impact_id}`.
  ///
  /// `organization_id` - ID (number) of the organization that contains the
  /// event. To get your `organization_id`, see
  /// [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).<br>
  /// `organization_impact_id` - ID of the [OrganizationImpact
  /// resource](/service-health/docs/reference/rest/v1beta/organizations.locations.organizationImpacts#OrganizationImpact).
  public var name: Swift.String = Swift.String()

  /// Output only. A list of event names impacting the asset.
  public var events: [Swift.String] = []

  /// Output only. Google Cloud asset possibly impacted by the specified events.
  public var asset: Asset? = nil

  /// Output only. The time when the affected project was last modified.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `OrganizationImpact`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrganizationImpact().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.OrganizationImpact"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
