// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents service health events that may affect Google Cloud products used
/// across the organization. It is a read-only view and does not allow any
/// modifications.
public struct OrganizationEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. Name of the event. Unique name of the event in
  /// this scope including organization ID and location using the form
  /// `organizations/{organization_id}/locations/{location}/organizationEvents/{event_id}`.
  ///
  /// `organization_id` - see [Getting your organization resource
  /// ID](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).<br>
  /// `location` - The location to get the service health events from.<br>
  /// `event_id` - Organization event ID to retrieve.
  public var name: Swift.String = Swift.String()

  /// Output only. Brief description for the event.
  public var title: Swift.String = Swift.String()

  /// Output only. Free-form, human-readable description.
  public var description: Swift.String = Swift.String()

  /// Output only. The category of the event.
  public var category: OrganizationEvent.EventCategory = OrganizationEvent.EventCategory()

  /// Output only. The detailed category of the event.
  public var detailedCategory: OrganizationEvent.DetailedCategory =
    OrganizationEvent.DetailedCategory()

  /// Output only. The current state of the event.
  public var state: OrganizationEvent.State = OrganizationEvent.State()

  /// Output only. The current detailed state of the incident.
  public var detailedState: OrganizationEvent.DetailedState = OrganizationEvent.DetailedState()

  /// Output only. Represents the Google Cloud products and locations impacted by
  /// the event.
  public var eventImpacts: [EventImpact] = []

  /// Output only. Incident-only field. Event updates are correspondence from
  /// Google.
  public var updates: [EventUpdate] = []

  /// Output only. When `detailed_state`=`MERGED`, `parent_event` contains the
  /// name of the parent event. All further updates will be published to the
  /// parent event.
  public var parentEvent: Swift.String = Swift.String()

  /// Output only. The time the update was posted.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The start time of the event, if applicable.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The end time of the event, if applicable.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Incident-only field. The time when the next update can be
  /// expected.
  public var nextUpdateTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `OrganizationEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrganizationEvent().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The category of the event. This enum lists all possible categories of
  /// event.
  public enum EventCategory: Codable, Equatable, Sendable {
    /// Unspecified category.
    case unspecified
    /// Event category for service outage or degradation.
    case incident
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .incident: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_CATEGORY_UNSPECIFIED"
      case .incident: return "INCIDENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_CATEGORY_UNSPECIFIED": self = .unspecified
      case "INCIDENT": self = .incident
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .incident
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .incident: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The detailed category of an event. Contains all possible states for all
  /// event categories.
  public enum DetailedCategory: Codable, Equatable, Sendable {
    /// Unspecified detailed category.
    case unspecified
    /// Indicates an event with category INCIDENT has a confirmed impact to at
    /// least one Google Cloud product.
    case confirmedIncident
    /// Indicates an event with category INCIDENT is under investigation to
    /// determine if it has a confirmed impact on any Google Cloud products.
    case emergingIncident
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .confirmedIncident: return 1
      case .emergingIncident: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DETAILED_CATEGORY_UNSPECIFIED"
      case .confirmedIncident: return "CONFIRMED_INCIDENT"
      case .emergingIncident: return "EMERGING_INCIDENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DetailedCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DETAILED_CATEGORY_UNSPECIFIED": self = .unspecified
      case "CONFIRMED_INCIDENT": self = .confirmedIncident
      case "EMERGING_INCIDENT": self = .emergingIncident
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DetailedCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .confirmedIncident
      case 2: self = .emergingIncident
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .confirmedIncident: return try container.encode(1)
      case .emergingIncident: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The state of the organization event. This enum lists all possible states of
  /// event.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Event is actively affecting a Google Cloud product and will continue to
    /// receive updates.
    case active
    /// Event is no longer affecting the Google Cloud product or has been merged
    /// with another event.
    case closed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .closed: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .closed: return "CLOSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CLOSED": self = .closed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .closed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .closed: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The detailed state of the incident. This enum lists all possible detailed
  /// states of an incident.
  public enum DetailedState: Codable, Equatable, Sendable {
    /// Unspecified detail state.
    case unspecified
    /// Google engineers are actively investigating the incident to determine the
    /// impact.
    case emerging
    /// The incident is confirmed and impacting at least one Google Cloud
    /// product. Ongoing status updates will be provided until it is resolved.
    case confirmed
    /// The incident is no longer affecting any Google Cloud product, and there
    /// will be no further updates.
    case resolved
    /// The incident was merged into a parent event. All further updates will be
    /// published to the parent only. The `parent_event` contains the name of the
    /// parent.
    case merged
    /// The incident was automatically closed because of the following reasons:
    ///
    ///  * The impact of the incident could not be confirmed.
    ///  * The incident was intermittent or resolved itself.
    ///
    ///  The incident does not have a resolution because no action or
    ///  investigation happened. If it is intermittent, the incident may reopen.
    case autoClosed
    /// Upon investigation, Google engineers concluded that the incident is not
    /// affecting a Google Cloud product. This state can change if the incident
    /// is reviewed again.
    case falsePositive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .emerging: return 1
      case .confirmed: return 2
      case .resolved: return 3
      case .merged: return 4
      case .autoClosed: return 9
      case .falsePositive: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DETAILED_STATE_UNSPECIFIED"
      case .emerging: return "EMERGING"
      case .confirmed: return "CONFIRMED"
      case .resolved: return "RESOLVED"
      case .merged: return "MERGED"
      case .autoClosed: return "AUTO_CLOSED"
      case .falsePositive: return "FALSE_POSITIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DetailedState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DETAILED_STATE_UNSPECIFIED": self = .unspecified
      case "EMERGING": self = .emerging
      case "CONFIRMED": self = .confirmed
      case "RESOLVED": self = .resolved
      case "MERGED": self = .merged
      case "AUTO_CLOSED": self = .autoClosed
      case "FALSE_POSITIVE": self = .falsePositive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DetailedState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .emerging
      case 2: self = .confirmed
      case 3: self = .resolved
      case 4: self = .merged
      case 9: self = .autoClosed
      case 10: self = .falsePositive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .emerging: return try container.encode(1)
      case .confirmed: return try container.encode(2)
      case .resolved: return try container.encode(3)
      case .merged: return try container.encode(4)
      case .autoClosed: return try container.encode(9)
      case .falsePositive: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.servicehealth.v1.OrganizationEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
