// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax

/// Request service health events relevant to your Google Cloud project.
///
/// @Snippet(path: "ServiceHealthQuickstart")
public final class ServiceHealthClient: Clients.ServiceHealthProtocol, Sendable {
  let inner: any Clients.ServiceHealthStub

  /// Creates a new `ServiceHealthClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServiceHealthStub = try Clients.ServiceHealthTransport(options)
    inner = Clients.ServiceHealthRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServiceHealthLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists events under a given project and location.
  ///
  /// @Snippet(path: "ServiceHealth_ListEvents")
  public func listEvents(
    request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse {
    try await self.inner.listEvents(request: request, options: options)
  }

  /// Lists events under a given project and location.
  ///
  /// @Snippet(path: "ServiceHealth_ListEvents")
  public func listEvents(
    byItem: ListEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Event, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEvents(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a resource containing information about an event.
  ///
  /// @Snippet(path: "ServiceHealth_GetEvent")
  public func getEvent(
    request: GetEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.Event {
    try await self.inner.getEvent(request: request, options: options)
  }

  /// Lists organization events under a given organization and location.
  ///
  /// @Snippet(path: "ServiceHealth_ListOrganizationEvents")
  public func listOrganizationEvents(
    request: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse {
    try await self.inner.listOrganizationEvents(request: request, options: options)
  }

  /// Lists organization events under a given organization and location.
  ///
  /// @Snippet(path: "ServiceHealth_ListOrganizationEvents")
  public func listOrganizationEvents(
    byItem: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOrganizationEvents(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a resource containing information about an event affecting an
  /// organization .
  ///
  /// @Snippet(path: "ServiceHealth_GetOrganizationEvent")
  public func getOrganizationEvent(
    request: GetOrganizationEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent {
    try await self.inner.getOrganizationEvent(request: request, options: options)
  }

  /// Lists assets impacted by organization events under a given organization and
  /// location.
  ///
  /// @Snippet(path: "ServiceHealth_ListOrganizationImpacts")
  public func listOrganizationImpacts(
    request: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse {
    try await self.inner.listOrganizationImpacts(request: request, options: options)
  }

  /// Lists assets impacted by organization events under a given organization and
  /// location.
  ///
  /// @Snippet(path: "ServiceHealth_ListOrganizationImpacts")
  public func listOrganizationImpacts(
    byItem: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOrganizationImpacts(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a resource containing information about impact to an asset under
  /// an organization affected by a service health event.
  ///
  /// @Snippet(path: "ServiceHealth_GetOrganizationImpact")
  public func getOrganizationImpact(
    request: GetOrganizationImpactRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact {
    try await self.inner.getOrganizationImpact(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ServiceHealth_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ServiceHealth_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ServiceHealth_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServiceHealthClient`.
  ///
  /// To mock `ServiceHealthClient` change your functions to receive
  /// `some ServiceHealthProtocol` or `any ServiceHealthProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServiceHealthProtocol {
    /// See `ServiceHealthClient.listEvents`.
    func listEvents(request: ListEventsRequest) async throws
      -> GoogleCloudServiceHealthV1.ListEventsResponse

    /// See `ServiceHealthClient.listEvents`.
    func listEvents(
      byItem: ListEventsRequest
    ) throws -> any AsyncSequence<Event, Swift.Error>

    /// See `ServiceHealthClient.listEvents`.
    func listEvents(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Event, Swift.Error>

    /// See `ServiceHealthClient.getEvent`.
    func getEvent(request: GetEventRequest) async throws -> GoogleCloudServiceHealthV1.Event

    /// See `ServiceHealthClient.getEvent`.
    func getEvent(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceHealthV1.Event

    /// See `ServiceHealthClient.listOrganizationEvents`.
    func listOrganizationEvents(request: ListOrganizationEventsRequest) async throws
      -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse

    /// See `ServiceHealthClient.listOrganizationEvents`.
    func listOrganizationEvents(
      byItem: ListOrganizationEventsRequest
    ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error>

    /// See `ServiceHealthClient.listOrganizationEvents`.
    func listOrganizationEvents(
      parent: Swift.String,
    ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error>

    /// See `ServiceHealthClient.getOrganizationEvent`.
    func getOrganizationEvent(request: GetOrganizationEventRequest) async throws
      -> GoogleCloudServiceHealthV1.OrganizationEvent

    /// See `ServiceHealthClient.getOrganizationEvent`.
    func getOrganizationEvent(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent

    /// See `ServiceHealthClient.listOrganizationImpacts`.
    func listOrganizationImpacts(request: ListOrganizationImpactsRequest) async throws
      -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse

    /// See `ServiceHealthClient.listOrganizationImpacts`.
    func listOrganizationImpacts(
      byItem: ListOrganizationImpactsRequest
    ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error>

    /// See `ServiceHealthClient.listOrganizationImpacts`.
    func listOrganizationImpacts(
      parent: Swift.String,
    ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error>

    /// See `ServiceHealthClient.getOrganizationImpact`.
    func getOrganizationImpact(request: GetOrganizationImpactRequest) async throws
      -> GoogleCloudServiceHealthV1.OrganizationImpact

    /// See `ServiceHealthClient.getOrganizationImpact`.
    func getOrganizationImpact(
      name: Swift.String,
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact

    /// See `ServiceHealthClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ServiceHealthClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ServiceHealthClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ServiceHealthClient.listEvents`.
    func listEvents(
      request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse

    /// See `ServiceHealthClient.listEvents`.
    func listEvents(
      byItem: ListEventsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Event, Swift.Error>

    /// See `ServiceHealthClient.getEvent`.
    func getEvent(
      request: GetEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.Event

    /// See `ServiceHealthClient.listOrganizationEvents`.
    func listOrganizationEvents(
      request: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse

    /// See `ServiceHealthClient.listOrganizationEvents`.
    func listOrganizationEvents(
      byItem: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error>

    /// See `ServiceHealthClient.getOrganizationEvent`.
    func getOrganizationEvent(
      request: GetOrganizationEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent

    /// See `ServiceHealthClient.listOrganizationImpacts`.
    func listOrganizationImpacts(
      request: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse

    /// See `ServiceHealthClient.listOrganizationImpacts`.
    func listOrganizationImpacts(
      byItem: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error>

    /// See `ServiceHealthClient.getOrganizationImpact`.
    func getOrganizationImpact(
      request: GetOrganizationImpactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact

    /// See `ServiceHealthClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ServiceHealthClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ServiceHealthClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.ServiceHealthProtocol {
  public func listEvents(request: ListEventsRequest) async throws
    -> GoogleCloudServiceHealthV1.ListEventsResponse
  {
    try await self.listEvents(request: request, options: .init())
  }

  public func listEvents(
    request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEvents(
    byItem: ListEventsRequest
  ) throws -> any AsyncSequence<Event, Swift.Error> {
    try self.listEvents(byItem: byItem, options: .init())
  }

  public func listEvents(
    byItem: ListEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Event, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEvents(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Event, Swift.Error> {
    let request = ListEventsRequest().with {
      $0.parent = parent
    }
    return try self.listEvents(byItem: request)
  }

  public func getEvent(request: GetEventRequest) async throws -> GoogleCloudServiceHealthV1.Event {
    try await self.getEvent(request: request, options: .init())
  }

  public func getEvent(
    request: GetEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.Event {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEvent(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceHealthV1.Event {
    let request = GetEventRequest().with {
      $0.name = name
    }
    return try await self.getEvent(request: request)
  }

  public func listOrganizationEvents(request: ListOrganizationEventsRequest) async throws
    -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse
  {
    try await self.listOrganizationEvents(request: request, options: .init())
  }

  public func listOrganizationEvents(
    request: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOrganizationEvents(
    byItem: ListOrganizationEventsRequest
  ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error> {
    try self.listOrganizationEvents(byItem: byItem, options: .init())
  }

  public func listOrganizationEvents(
    byItem: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrganizationEvents(
    parent: Swift.String,
  ) throws -> any AsyncSequence<OrganizationEvent, Swift.Error> {
    let request = ListOrganizationEventsRequest().with {
      $0.parent = parent
    }
    return try self.listOrganizationEvents(byItem: request)
  }

  public func getOrganizationEvent(request: GetOrganizationEventRequest) async throws
    -> GoogleCloudServiceHealthV1.OrganizationEvent
  {
    try await self.getOrganizationEvent(request: request, options: .init())
  }

  public func getOrganizationEvent(
    request: GetOrganizationEventRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOrganizationEvent(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent {
    let request = GetOrganizationEventRequest().with {
      $0.name = name
    }
    return try await self.getOrganizationEvent(request: request)
  }

  public func listOrganizationImpacts(request: ListOrganizationImpactsRequest) async throws
    -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse
  {
    try await self.listOrganizationImpacts(request: request, options: .init())
  }

  public func listOrganizationImpacts(
    request: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOrganizationImpacts(
    byItem: ListOrganizationImpactsRequest
  ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error> {
    try self.listOrganizationImpacts(byItem: byItem, options: .init())
  }

  public func listOrganizationImpacts(
    byItem: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrganizationImpacts(
    parent: Swift.String,
  ) throws -> any AsyncSequence<OrganizationImpact, Swift.Error> {
    let request = ListOrganizationImpactsRequest().with {
      $0.parent = parent
    }
    return try self.listOrganizationImpacts(byItem: request)
  }

  public func getOrganizationImpact(request: GetOrganizationImpactRequest) async throws
    -> GoogleCloudServiceHealthV1.OrganizationImpact
  {
    try await self.getOrganizationImpact(request: request, options: .init())
  }

  public func getOrganizationImpact(
    request: GetOrganizationImpactRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOrganizationImpact(
    name: Swift.String,
  ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact {
    let request = GetOrganizationImpactRequest().with {
      $0.name = name
    }
    return try await self.getOrganizationImpact(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
