// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ServiceHealthLogging: ServiceHealthStub {
    let inner: any ServiceHealthStub
    let logger: Logger

    public init(_ inner: any ServiceHealthStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-servicehealth-v1"
      logger[metadataKey: "gcp.client.service"] = "servicehealth"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ServiceHealth"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listEvents(
      request: ListEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEvents",
        action: {
          (r: ListEventsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListEventsResponse
          in
          return try await self.inner.listEvents(request: r, options: o)
        })
    }

    public func getEvent(
      request: GetEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEvent",
        action: {
          (r: GetEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.Event
          in
          return try await self.inner.getEvent(request: r, options: o)
        })
    }

    public func listOrganizationEvents(
      request: ListOrganizationEventsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOrganizationEvents",
        action: {
          (r: ListOrganizationEventsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse
          in
          return try await self.inner.listOrganizationEvents(request: r, options: o)
        })
    }

    public func getOrganizationEvent(
      request: GetOrganizationEventRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOrganizationEvent",
        action: {
          (r: GetOrganizationEventRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.OrganizationEvent
          in
          return try await self.inner.getOrganizationEvent(request: r, options: o)
        })
    }

    public func listOrganizationImpacts(
      request: ListOrganizationImpactsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOrganizationImpacts",
        action: {
          (r: ListOrganizationImpactsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse
          in
          return try await self.inner.listOrganizationImpacts(request: r, options: o)
        })
    }

    public func getOrganizationImpact(
      request: GetOrganizationImpactRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOrganizationImpact",
        action: {
          (r: GetOrganizationImpactRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.OrganizationImpact
          in
          return try await self.inner.getOrganizationImpact(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
