// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class ServiceHealthRetry: ServiceHealthStub {
    let inner: any ServiceHealthStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ServiceHealthStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listEvents(
      request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEventsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListEventsResponse
          in
          return try await self.inner.listEvents(request: r, options: o)
        })
    }

    public func getEvent(
      request: GetEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.Event {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEventRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.Event
          in
          return try await self.inner.getEvent(request: r, options: o)
        })
    }

    public func listOrganizationEvents(
      request: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOrganizationEventsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse
          in
          return try await self.inner.listOrganizationEvents(request: r, options: o)
        })
    }

    public func getOrganizationEvent(
      request: GetOrganizationEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOrganizationEventRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.OrganizationEvent
          in
          return try await self.inner.getOrganizationEvent(request: r, options: o)
        })
    }

    public func listOrganizationImpacts(
      request: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOrganizationImpactsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse
          in
          return try await self.inner.listOrganizationImpacts(request: r, options: o)
        })
    }

    public func getOrganizationImpact(
      request: GetOrganizationImpactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOrganizationImpactRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudServiceHealthV1.OrganizationImpact
          in
          return try await self.inner.getOrganizationImpact(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
