// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol ServiceHealthStub: Sendable {
    func listEvents(
      request: ListEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListEventsResponse

    func getEvent(
      request: GetEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.Event

    func listOrganizationEvents(
      request: ListOrganizationEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationEventsResponse

    func getOrganizationEvent(
      request: GetOrganizationEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationEvent

    func listOrganizationImpacts(
      request: ListOrganizationImpactsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.ListOrganizationImpactsResponse

    func getOrganizationImpact(
      request: GetOrganizationImpactRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudServiceHealthV1.OrganizationImpact

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
